spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forTest?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.meet5.pojo
  type-handlers-package: com.meet5.handler
